### ISSUE TITLE
Protobuf compiler roadmap

### ISSUE THREAD

**Issue by Marik-D** [dxos/codec-protobuf#21]
- [ ] Better error handling + diagnostic messages
- [ ] Add typescript to peer dependencies and check version at runtime
- [ ] Better oneof support
- [ ] Cross-module imports
- [ ] Joining substitutions imported from multiple modules
